function idklol() {
    document.getElementById("color").innerHTML = getRandomSentence();   
}

function getRandomSentence() {
    const fruits = ["Cookies","THE FACTORY MUST GROW","Lorem ipsum dolor sit amet" ,"(defun botsbuildbots () (botsbuildbots))" , "I CENTER DIV EZ YIPPYYYYYYYYYY" , "Hey bro, got any  <I><u><b>UPSHOW</b></u></i>?", "", "Made with the Shapez 2 soundtrack!", "Welcome to the Information Superhighway!",
        "life is MS Paint, MS Paint is life.", ":GD_Normal:" ,"FIRE IN THE HOLE", "WATER ON THE HILL", "ROCK ON THE GROUND", "AREA CONFIRMED", "AIR DETECTED", "BLOOD IN THE BATH", "KIDS AT THE BASEMENT", "WE WORK, TO EARN THE RIGHT TO WORK", "Welcome to the Information Superhighway!" ,"The secret to happiness is --DATA_CORRUPTED--", "<🅱️r>",
        ,"You can't stop progress.", "We're all in it together.", "88888888888888888888888888" , ":sentry:" , "engineer gaming", "Sentry goin up!","Dispenser down!","it starts with","The engineer is engi-here!","moe", "BONK"
        ,"BOINK","CAUTION: Spinny thing go fast.", "Today is amazing midday!", "test", "BEEP-BOOP, I AM A ROBOT, I HAVE COME TO TAKE AMERICAN JOBS!", "xd is DOMINATING Average Linux user!", "xd is DOMINATING Average Windows user!", "1+1=4137843", "Number 19, mouse in baked beans.", "Theres a spy creeping around here!", "I am a", "xee xorb xi xam",
        "play tf2", "We work, to earn the right to work.", "Ubuntu gaming", "The cake is a lie","I'm going to k&nbsp;i&nbsp;l&nbsp;l you and all the cake is gone.","It's big brain time.","Oh yeah, it's big brain time.","Made with old computers, &quot;computers&quot;, and cables!", "Your mom","Your doin good lad!","NATURALLY AND ARTIFICIALLY FLAVORED", "KABLUEY",
        "`1234567890-=","qwertyuiop[]","sdfghjkl;'","zxcvbnm,./","Not aproved by the FDA!","1=1","No Brainrot Zone!","Oxygen Not Included!","Also Comes in <u><b>Grape!</b><u/>","Why's this dealer (do do) taken a pisss ive been standing here (do do) for 30 minutes.","The Data Won't Corrupt Itself!","The Data Won't Collate Itself!","All That Code Won't Compile Itself!",
        "SSSPAAAAAAAAACCCCCCCCCEEEEEEEEEEEEE","glorp zorp","linux gaming","Stickman CPU inside!","Stickman GPU inside!","Made with 74.903 Novemdecillion Cookies!","Go finish your homework.","Go finish your homework.","Go finish your homework.","Go finish your homework.","Go finish your homework.","Go finish your homework.","Go finish your homework.","Go finish your homework.",
        ,"The cake is a lie.","I LOVE CSS","100% Free Range Code!*","*Code may not be free range lol","The Gizmo-gadget-thingamajig.","μ","⺺⑤■⩹ⶺ⍸⛱⮲Ⓘⳕ","ↀ℆℧⅋ℬKKℳⅪⅭⅯↇℂℿ℠⅞⅖⅘ⅾ⅑Ⅳ⅃Ⅲℶⅶ⅛℡ℙↁ℺⅟⅛⅊Ⅺ⅝⅝⅚℥⅊№ⅲ℔ℌℏℝ℘Ⅽ℡⅄ⅢⅮℝ⅗℺ℨⅤ⅂ℐℹⅽ℘ↀ⅙⅘Ⅸ⅍","🅱️","A 3 piece Bicken nugget?","A Large Boke?" ,"And 3 Bhocolate Bhip Bookies?", "weeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee","Ctrl+I to continue with Copilot",
        "YEEEEE HEEEEE, HIC-ADDEEEE HEEEEEEEE!!!!!!","Science is Fun","Concentration Enhancing Menu Initialiser...","Comedy = Tragedy + Time","I AM NOT A MORON!","Reconstructing More Science...","This The Part Where He Kills You.","Made with 33.3% Greg, 33.3% Tech and 33.4% New Horizons!","Doc come on man!","this a very Cool-Website indeed","gigafart windows PC","terafart linux PC","Milk + powdered milk = 200% milk.",
        "Theres a spy sappin' my sentry!","You Will Be Baked, And Then There Will Be Cake.","You Will Be Evaluated.","Sentry mode activated.","I'm Different.","YEEEEEEEEEE HAAAAAAAAAAA","jkm","dosdpdpdpddp","Not USB compatible!","Super Duper Ultra Mega Hyper Multi Alpha Meta Extra Über Charge Ready!","idklol()",";lsdfjjkrjj54jfejf,","q","Über Charge Ready!","WE LIVE IN A WORLD OF GOO",
    "15 engies in red intel.","Held together by hope, dreams, and FICSIT duct tape.","The MACHINE is here.","eeeeeeeeeeeeeeeeeeeeeeeeeeeeee","See you on monday!","I am speed.&nbsp;&nbsp;&nbsp; KACHOW","KACHOW","Wake up. Wake up. Wake up. Wake up. Wake up. Wake up. Wake up. ","THE FOG IS COMING. ","AUGUST 12 2036, THE HEAT DEATH OF THE UNIVERSE.","ERR: 413 - TO MUCH BRAINROT IN USER.","The testing begins.",
    "asdasdsadasdasd","<>{}[]","You Will Be Perfect For The Test.","goo goo gaga, i want milk.","dpojwp","i am gaming","dsfkf.,gjxkmlfgkcl","THAT'S A LOT OF DAMAGE","That engineer is a spy!","That Engineer is a gamer!","Welcome to the Information Superhighway!","Shuting down...","As an AI I just cant lol","Satisfactory!","%killername%","Did Cookie Clicker just get a minor update... ITS ALIVEEEEEEE","HalF-LiFe 3 CoNfiRmEd?!","hunger","Yummers!",
    "open the nor","OPEN THE NOR","I'm gona hit the F25 key","F25 key? Are you ready for this? Promise not to tell. I'm gonna hit the f25 key, get ready!","AHH QWERT*&DFRP(IJFHI?SHO:KZPICIKO","𝗦𝗽𝗮𝗴𝗵𝗲𝘁𝘁𝗶𝗳𝗶𝗰𝗮𝘁𝗶𝗼𝗻 𝗘𝘃𝗲𝗻𝘁 𝗜𝗺𝗺𝗶𝗻𝗲𝗻𝘁.","wasd","1 / 0 = black hole","getRandomSentence","linux","That engineer is gaming!","It's time. To Burn Your House Down!","Rain Rain Windy Windy","Open Source!"
    ,"gee gorp","Unaproved by the FBI!","Unaproved by the CIA!","i am killer fish from san diego",":","I eat uranium-235 every day.","we snaw","snaw we","i love cookie clicker","that's right! it goes in the square hole.","Zoo wee mama!", "Welcome to the Information Superhighway!", "Welcome to the Information Superhighway!", "Welcome to the Information Superhighway!","well, well, well if it isn't CSS again.",
    "gamer@terafart:~$ ","GEOMETRY DASH","SHADOW WIZARD MONEY GANG, WE LOVE CASTING SPELLS","It's not a bug, it's a feature.","Press PP button now!","3110","Nyoom is happening","time","I Nyoom Nyoom Nyoom Nyoom nugget","Speedy thing goes in, speedy thing comes out.","I am slow.","snap","goo game","null","I AM NOT A MORON!","Red Spy In Base","http://127.0.0.1:5500/","THE FACTORY MUST GROW","cz-shortcut-listen=&quot;true&quot;"
,"lol","I, Am Steve.","^C","^V","yee haaawww","-xd","16 // 16 // 16","THE SUN IS LEAKING","bro im the bigest brid","Technoblade never dies!","You should sudo rm -rf yourself NOW!","LEGALIZE NUCLEAR BOMBS","WHAT THE F**K IS A KILOMETERRRR","Go for the coin!","FICIT duct tape","spy creepin' around here!","Hey boys, it's a spy!","Spy around here","Yummers!","Testing is the Future, and the Future starts with you.","The details of the MACHINE will show them self when you see it."
     ];
    const randomIndex = Math.floor(Math.random() * fruits.length);
    const result = fruits[randomIndex];
    return result;
}